#!/bin/bash

# first 50 files
counter=0
for f in *.com; do
IN=$f
JOB=${IN%.*}

if test -f "$JOB.log"; then 
	echo "$JOB.log exists, not submitting"
fi

if [ ! -f $JOB".log" ]; then 
counter=$(($counter+1))

if [ $counter -gt 1107 ]; then
break
fi

	SUBMIT=qsub.tmp
	PWD=`pwd`

	cat > $SUBMIT <<!EOF
#!/bin/bash
#SBATCH --job-name=$JOB
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=4G
#SBATCH --partition=normal,classic,highermem,hishort


# Export variables
export GAUSS_EXEDIR=/home/puck/opt/gaussian_09
export G09=\$GAUSS_EXEDIR/g09
export PATH=$GAUSS_EXEDIR:$PATH
export GAUSS_SCRDIR=/scratch/puck/g09_`uuidgen`


# Check if local scratch directory exists
if [ ! -d \$GAUSS_SCRDIR ]; then
        mkdir \$GAUSS_SCRDIR
fi

# Run g09
cd $PWD
\$G09 $IN

# Clean-up local scratch-dir
rm -r \$GAUSS_SCRDIR

!EOF

sbatch $SUBMIT
rm $SUBMIT
fi
done
